// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolHub.Models;

public partial class Sibling
{
    public int Id { get; set; }

    public string SiblingName { get; set; }

    public int? StudentId { get; set; }

    public virtual Student Student { get; set; }
}